name: Java CI with Gradle

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Zip create
        run: |
          cd build/libs
          zip release *.*

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Release
          path: build/libs

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: OtyacraftEngine - ${{ steps.get_version.outputs.version }}
          body: |
            The New Release!
            Build by ${{ github.actor }}
          draft: false
          prerelease: false

      - uses: xresloader/upload-to-github-release@v1
        name: Upload Release File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          file: "build/libs"
          tags: true
          draft: false
          tag_name: ${{ steps.get_version.outputs.version }}